### PR TITLE
8302857: Generational ZGC: enable correctness barrier elision tests on all platforms

### PR DESCRIPTION
**Pull request by robcasloz**
This changeset splits the recent barrier elision tests added by [JDK-8301584](https://bugs.openjdk.org/browse/JDK-8301584) and extended by [JDK-8301769](https://bugs.openjdk.org/browse/JDK-8301769) into correctness tests (do not elide necessary barriers) and effectiveness tests (do elide unnecessary barriers), and enables the former on all platforms that support ZGC, following the [discussion on JDK-8301769](https://github.com/openjdk/zgc/pull/13).

{@TheRealMDoerr, @RealFYang}: could you please check whether the updated tests pass on the other ZGC-supporting platforms?

**Testing:** re-run the updated tests (x64 and aaarch64; linux, windows, and macosx; release and debug mode)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8302857](https://bugs.openjdk.org/browse/JDK-8302857): Generational ZGC: enable correctness barrier elision tests on all platforms

### Reviewers
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/zgc pull/14/head:pull/14` \
`$ git checkout pull/14`

Update a local copy of the PR: \
`$ git checkout pull/14` \
`$ git pull https://git.openjdk.org/zgc pull/14/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14`

View PR using the GUI difftool: \
`$ git pr show -t 14`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/zgc/pull/14.diff">https://git.openjdk.org/zgc/pull/14.diff</a>

</details>

### CODE REVIEW

**Comment by RealFYang** [comment]
Hi, this passed with fastdebug build on linux-riscv:
```
Running test 'jtreg:./test/hotspot/jtreg/compiler/gcbarriers/TestZGCBarrierElision.java'
Passed: compiler/gcbarriers/TestZGCBarrierElision.java#id0
Test results: passed: 1
```

**Comment by robcasloz** [comment]
> Hi, this passed with fastdebug build on linux-riscv:

Thanks for checking, @RealFYang !

**Comment by TheRealMDoerr** [comment]
Hi, the test has passed on PPC64le, too. Thanks!

**Comment by robcasloz** [comment]
> Hi, the test has passed on PPC64le, too. Thanks!

Great, thanks for checking @TheRealMDoerr !

**Review by fisk — APPROVED** [review]
Looks good.

**Comment by robcasloz** [comment]
> Looks good.

Thanks for reviewing, Erik!

**Pull request closed without merging**
