### PR TITLE
8295842: Generational ZGC: Elide barriers on variable array accesses after array allocations

### PR DESCRIPTION
**Pull request by robcasloz**
This changeset extends C2's barrier elision so that variable array accesses (array accesses with unknown offset at compile-time) are elided when they are dominated by the array's allocation and no safepoint is present in between, like in this example:

```
Element[] a = new Element[10]; // allocation
a[i] = e; // variable array access: the barrier is elided
```

This is achieved by relaxing the dominator-dominated pair test in [zBarrierSetC2.cpp](https://github.com/openjdk/zgc/blob/a460756f08df30af232fc631e94cf37c10c38352/src/hotspot/share/gc/z/c2/zBarrierSetC2.cpp#L714) so that unknown memory access offsets are accepted for array allocation dominators.

This refinement does not yield significant overall throughput changes in standard benchmark suites (DaCapo, SPECjvm2008), but has been observed to at least elide a few additional  barriers in individual benchmarks, e.g. DaCapo's H2:

```
Value[] keyValues = new Value[groupIndex.length]; // array allocation
// update group
for (int i = 0; i < groupIndex.length; i++) {
    int idx = groupIndex[i];
    Expression expr = expressions.get(idx);
    keyValues[i] = expr.getValue(session); // store barrier is elided by this changeset
}
```

#### Testing

- tier1-5 (windows-x64, linux-x64, linux-aarch64, macosx-x64, and macosx-aarch64; release and debug mode)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295842](https://bugs.openjdk.org/browse/JDK-8295842): Generational ZGC: Elide barriers on variable array accesses after array allocations

### Reviewers
 * [Erik Österlund](https://openjdk.org/census#eosterlund) (@fisk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/zgc pull/8/head:pull/8` \
`$ git checkout pull/8`

Update a local copy of the PR: \
`$ git checkout pull/8` \
`$ git pull https://git.openjdk.org/zgc pull/8/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8`

View PR using the GUI difftool: \
`$ git pr show -t 8`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/zgc/pull/8.diff">https://git.openjdk.org/zgc/pull/8.diff</a>

</details>

### CODE REVIEW

**Comment by fisk** [comment]
You changed get_base_and_offset to return the base even if the offset < 0, and then where get_base_and_offset is used, you check if the offset is < 0 and treat it as if the base returned NULL. Why is that? Is it because there is some kind of array case we want to optimize for, where the offset is negative but valid?

**Comment by robcasloz** [comment]
Thanks for looking at this, Erik!

> You changed get_base_and_offset to return the base even if the offset < 0, and then where get_base_and_offset is used, you check if the offset is < 0 and treat it as if the base returned NULL. Why is that? Is it because there is some kind of array case we want to optimize for, where the offset is negative but valid?

Right. An offset can be a special value `Type::OffsetTop` (-2000000000, representing undefined values), a special value `Type::OffsetBot` (-2000000001, representing unknown values), or a concrete value. Before this PR, we simply required that offsets be concrete and >= 0. The initial version of this PR relaxes this requirement to accept unknown offsets (with offset `Type::OffsetBot`) in allocation-dominated array accesses:

```
  Element[] a = new Element[10]; // allocation
  a[i] = e; // variable array access with unknown offset
```

  I have pushed (and re-tested) a new version that makes offset tests more explicit, documents what is expected in each case using assertions, and actually discards candidate array accesses with undefined or concrete-but-negative offsets (which was simply assumed to not happen in the previous revision). Please let me know whether this makes the changes clearer.

**Review by fisk — APPROVED** [review]
Thanks for the explanation Roberto. Looks good.

**Comment by robcasloz** [comment]
> Thanks for the explanation Roberto. Looks good.

Thanks, Erik!

**Pull request closed without merging**
