### PR TITLE
RISC-V: Only use conditional far branch in copy_memory for ZGC

### PR DESCRIPTION
**Pull request by RealFYang**
The size of 'copy32_loop' body in copy_memory increases significantly with ZGC GC barriers on RISC-V. So we need to use conditional far branches to reach a point beyond the loop. But we don't need that for other cases. Conditional short branches which are simpler /faster will do for other GCs. This also removes the vectorized BarrierSetAssembler::copy_load_at/copy_store_at as they are not implemented/used for now.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/zgc pull/16/head:pull/16` \
`$ git checkout pull/16`

Update a local copy of the PR: \
`$ git checkout pull/16` \
`$ git pull https://git.openjdk.org/zgc pull/16/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16`

View PR using the GUI difftool: \
`$ git pr show -t 16`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/zgc/pull/16.diff">https://git.openjdk.org/zgc/pull/16.diff</a>

</details>

### CODE REVIEW

**Comment by RealFYang** [comment]
@fisk : Could you please take a look and integrate it if it's OK? Thanks.

**Comment by fisk** [comment]
Seems fine to me!

**Comment by RealFYang** [comment]
> Seems fine to me!

Thanks for looking at this. I did a merge and removed the vectorized BarrierSetAssembler::copy_load_at/copy_store_at functions as they are not implemented/used for now.

**Comment by RealFYang** [comment]
@fisk : Hi, the riscv is broken on the latest zgc_generational branch. I see the branch instructions here are erroneously changed to the short version when rebasing. This could be resolved if this PR gets merged. Could you please help do the integration? Thanks.

**Pull request merged**
